#pragma once

#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          16
#define MOUSEKEY_MAX_SPEED         7
#define MOUSEKEY_TIME_TO_MAX       40
#define MOUSEKEY_WHEEL_MAX_SPEED   1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 255

#define RGB_DI_PIN D0
#define RGBLED_NUM 3
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17
#define RGBLIGHT_LIMIT_VAL 255
#define RGBLIGHT_SLEEP
#define BACKLIGHT_LED_COUNT 3
#define BACKLIGHT_LEVELS 1

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define RETRO_TAPPING
